### PR TITLE
Upgrade DaisySP to newest version

### PR DESCRIPTION
**Pull request by chmanie**
I took the liberty of upgrading DaisySP to the newest version. As there is no clear version and this was just copied over, I can't really be sure.

For the next person doing this tedious task, the DaisySP commit DaisyDuino is based on now is [`4263388`](https://github.com/electro-smith/DaisySP/commit/4263388e7fa8dfd34fa85c6a1c697362dc6981c7).

This adds support for the new FIR, Looper and Phaser classes as well as some new utility functions like `fmap`.

### CODE REVIEW

**Comment by stephenhensley** [comment]
@chmanie thanks for the contribution!

We'll take look over the changes, and get this merged in!

Good point about the versioning of the C++ DaisySP. The plan is to implement a sem-ver based versioning system similar to what's used in the libDaisy library, but we haven't gotten around to it quite yet.

**Comment by chmanie** [comment]
Sorry for the weird diff, I don't really know what happened here. Could this be a tabs vs. space problem?

**Comment by beserge** [comment]
# Changes
- If you could add the new classes to `keywords.txt` so they syntax highlight correctly that would be great.

Once that's complete, I say it's ready to merge!
Thanks for your contribution! 🎆 

# Test Procedure
All tests were performed on the Daisy Patch, with a rev4 seed.

Flashed some of the examples that were touched with just line endings and so on.
seed/adsr, seed/bitcrush, seed/decimator

Made an example initializing each of the new modules (FIR, Looper, Phaser) and setting some parameters and made sure they compiled.

**Comment by chmanie** [comment]
@beserge Thank you so much for the thorough review. I added the relevant keywords and fixed some ordering/naming issues on the way.

**Pull request merged**
