### PR TITLE
Stmduino control bugfix

### LINKED ISSUE #30: Controls no longer work with stm32duino update
Controls stopped working since stm32duino update. Not sure why yet, need to look into it.

### PR DESCRIPTION
**Pull request by beserge**
Fixes #30 

Tested a bit on the patch, works great, Needs to be tested on the rest of our hardware.
Also: need to go through and confirm none of the example sketches have hardcoded analog reads hanging around.

### CODE REVIEW

**Comment by beserge** [comment]
[Fix daisyduino controls broken by stm32duino update](https://trello.com/c/fGjulf6j/130-fix-daisyduino-controls-broken-by-stm32duino-update)

**Comment by stephenhensley** [comment]
This and #29 seem solid

tested the field, and everything seems to be working as expected. Still wanna check on the pod/petal before merging and making a release, but you can go ahead and update the `library.properties` file to have `v1.4.0` for when we publish it.

**Comment by stephenhensley** [comment]
So Pod, Field, Petal all check out from a control point of view, but I'm getting some serious performance issues on anything that uses the RAM, which makes me think either the MPU, or the Cache aren't getting initialized/enabled correctly. 

Would be worth looking through the changes here and in the stm32duino changes to see if anything's too different that could be causing this. (Also probably worth checking if it's unique to the Pedal or not, because that's the only board I noticed it on).

**Comment by stephenhensley** [comment]
good catch on the extra bugs!

Think this is good to go. Tested a few other examples to make sure, but everything seems solid.

**Pull request merged**
